output "ec2_instance_public_ip" {
  description = "Public IP of the EC2 instance"
  value       = aws_instance.instance.public_ip
}

output "ec2_instance_public_dns" {
  description = "Public DNS of the EC2 instance"
  value       = aws_instance.instance.public_dns
}

output "ssh_private_key_path" {
  description = "Path to your SSH private key (if generated by Terraform)"
  value       = "~/.ssh/id_rsa"
}

output "kubeconfig_note" {
  description = "Access the K3s cluster by SSHing into the instance and using this path"
  value       = "Run: ssh -i ~/.ssh/id_rsa ubuntu@${aws_instance.instance.public_ip} && sudo cat /etc/rancher/k3s/k3s.yaml"
}
